### PR TITLE
allow to transparently run on cpython wasm + pygame-ce

### PR DESCRIPTION
**Pull request by pmp-p**
eg https://pmp-p.ddns.net/pygbag/wip/pyved-engine/examples/platformer0/build/web/

### CODE REVIEW

**Comment by wkta** [comment]
cool ! The line:
`await asyncio.sleep(0)` is intringuing tho.
Can you please describe in comment what is its role ? @pmp-p

**Comment by wkta** [comment]
I mean : what other task is running, so its required to give execution access? via this `sleep(0) `call ?

**Comment by pmp-p** [comment]
> what other task is running

the browser javascript + browser io synchronous loop
```
io:
--> js
     --->
          wasm/python
      <---
   js
goto io
```
asyncio.sleep(0) woule be much like "yield" in context of js calling a python renderframe()

**Review by wkta — APPROVED** [review]
All good, thank you for the suggestion

**Pull request merged**
